### ISSUE TITLE
ReadResponse in Response Close() hang

### ISSUE THREAD

**Issue by Speedy37** [jlaffaye/ftp#117]
I was trying out rclone with restic and I got stuck by ReadResponse in Response Close() hanging. 

And it seems to never timeout.

**Comment by Speedy37** [comment]
Here is a tcpdump result:

```
19:37:17.867894 IP client.47852 > server.21: FTP: MLSD .
19:37:17.868153 IP server.21 > client.47852: FTP: 150 Accepted data connection
19:37:17.868278 IP server.21 > client.47852: FTP: 226-Options: -a -l
19:37:17.869176 IP client.47852 > server.21: FTP: EPSV
19:37:17.869454 IP server.21 > client.47852: FTP: 229 Extended Passive mode OK (|||14537|)
19:37:17.869911 IP client.47852 > server.21: FTP: MLSD .
19:37:17.870128 IP server.21 > client.47852: FTP: 150 Accepted data connection
19:37:17.870237 IP server.21 > client.47852: FTP: 226-Options: -a -l
19:37:17.870935 IP client.47852 > server.21: FTP: EPSV
19:37:17.871184 IP server.21 > client.47852: FTP: 229 Extended Passive mode OK (|||13091|)
19:37:17.871593 IP client.47852 > server.21: FTP: MLSD keys
19:37:17.871856 IP server.21 > client.47852: FTP: 150 Accepted data connection
19:37:17.871955 IP server.21 > client.47852: FTP: 226-Options: -a -l
19:37:17.872937 IP client.47852 > server.21: FTP: EPSV
19:37:17.873243 IP server.21 > client.47852: FTP: 229 Extended Passive mode OK (|||10308|)
19:37:17.873637 IP client.47852 > server.21: FTP: MLSD keys
19:37:17.874011 IP server.21 > client.47852: FTP: 150 Accepted data connection
19:37:17.874084 IP server.21 > client.47852: FTP: 226-Options: -a -l
19:37:17.874264 IP client.47852 > server.21: FTP: EPSV
19:37:17.874647 IP server.21 > client.47852: FTP: 229 Extended Passive mode OK (|||19965|)
19:37:17.874976 IP client.47852 > server.21: FTP: RETR keys/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
19:37:17.875237 IP server.21 > client.47852: FTP: 150 Accepted data connection
19:37:17.875367 IP server.21 > client.47852: FTP: 226-File successfully transferred
19:37:18.240540 IP client.47852 > server.21: FTP: EPSV
19:37:18.240851 IP server.21 > client.47852: FTP: 229 Extended Passive mode OK (|||14811|)
19:37:18.241336 IP client.47852 > server.21: FTP: MLSD .
19:37:18.241588 IP server.21 > client.47852: FTP: 150 Accepted data connection
19:37:18.241668 IP server.21 > client.47852: FTP: 226-Options: -a -l
19:37:18.241827 IP client.47852 > server.21: FTP: EPSV
19:37:18.242020 IP server.21 > client.47852: FTP: 229 Extended Passive mode OK (|||15138|)
19:37:18.242367 IP client.47852 > server.21: FTP: RETR config
19:37:18.242634 IP server.21 > client.47852: FTP: 150 Accepted data connection
19:37:18.242710 IP server.21 > client.47852: FTP: 226-File successfully transferred
19:37:18.298152 IP client.47852 > server.21: FTP: EPSV
19:37:18.298461 IP server.21 > client.47852: FTP: 229 Extended Passive mode OK (|||15320|)
19:37:18.298904 IP client.47852 > server.21: FTP: MLSD index
19:37:18.299345 IP server.21 > client.47852: FTP: 150 Accepted data connection
19:37:18.299429 IP server.21 > client.47852: FTP: 226-Options: -a -l
19:37:18.444479 IP client.47852 > server.21: FTP: EPSV
19:37:18.444945 IP server.21 > client.47852: FTP: 229 Extended Passive mode OK (|||19599|)
19:37:18.445308 IP client.47852 > server.21: FTP: MLSD snapshots
19:37:18.445572 IP server.21 > client.47852: FTP: 150 Accepted data connection
19:37:18.445640 IP server.21 > client.47852: FTP: 226-Options: -a -l
19:37:18.518187 IP client.47852 > server.21: FTP: EPSV
19:37:18.519173 IP server.21 > client.47852: FTP: 229 Extended Passive mode OK (|||14233|)
19:37:18.519768 IP client.47852 > server.21: FTP: MLSD data/01
19:37:18.520015 IP server.21 > client.47852: FTP: 150 Accepted data connection
19:37:18.520148 IP server.21 > client.47852: FTP: 226-Options: -a -l
19:37:18.520474 IP client.47852 > server.21: FTP: EPSV
19:37:18.520719 IP server.21 > client.47852: FTP: 229 Extended Passive mode OK (|||17257|)
19:37:18.521114 IP client.47852 > server.21: FTP: REST 3567097
19:37:18.521342 IP server.21 > client.47852: FTP: 350 Restarting at 3567097
19:37:18.521407 IP client.47852 > server.21: FTP: RETR data/01/xxxxxxxxxxxxxxxxxxxxxxxxxx
19:37:18.521708 IP server.21 > client.47852: FTP: 150-Accepted data connection
19:37:22.952641 IP server.21 > client.47852: FTP: 150 Logout.
```

**Comment by Speedy37** [comment]
My understanding is: restic|rclone Close the response before finishing reading it completely.

**Comment by corny** [comment]
It might help to don't read if `Close()` failed. Try this:

```golang
func (r *Response) Close() error {
	if err := r.conn.Close(); err != nil {
		return err
	}

	_, _, errr := r.c.conn.ReadResponse(StatusClosingDataConnection)
	return err
}
```

I also think the `closed` variable can be omitted.

**Comment by Speedy37** [comment]
Well r.conn.Close() always returns nil in my test case.

**Comment by mikeb333** [comment]
Any update on this?  I am running into the same issue. The ftp server never sends back a StatusClosingDataConnection response so the Close() method hangs.

**Comment by jlaffaye** [comment]
I think we should send an ABOR command when closing the data connection before EOF.

**Comment by jeffquinn-bluevoyant** [comment]
Hello, I'm also hitting this same issue via Rclone. Mine occurs during the List method. Heres a stacktrace showing where the hang is.

```
goroutine 72 [IO wait, 1083 minutes]:
internal/poll.runtime_pollWait(0x7f0dfcd00e30, 0x72, 0xc0000cb780)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000346018, 0x72, 0xffffffffffffff00, 0x146c4e0, 0x1d58830)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000346018, 0xc000348000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000346000, 0xc000348000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000346000, 0xc000348000, 0x1000, 0x1000, 0xc000644a80, 0x300000002, 0xc000644a80)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000ec40, 0xc000348000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x68
bufio.(*Reader).fill(0xc000229800)
	/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).ReadSlice(0xc000229800, 0x4a7c0a, 0xc000106100, 0x1, 0xc0000cb900, 0xc0000cb9a0, 0x4a9050)
	/usr/local/go/src/bufio/bufio.go:341 +0x36
bufio.(*Reader).ReadLine(0xc000229800, 0xc0000cba00, 0xc0000cb9e0, 0x43660c, 0xc000644a80, 0x300000002, 0xc000644a80)
	/usr/local/go/src/bufio/bufio.go:370 +0x34
net/textproto.(*Reader).readLineSlice(0xc000227dd0, 0x4406dc, 0xc000106128, 0xc0000cba01, 0x4405bb, 0xc000106128)
	/usr/local/go/src/net/textproto/reader.go:55 +0x6f
net/textproto.(*Reader).ReadLine(0xc000227dd0, 0x0, 0x0, 0xc0000cbab0, 0x4404d9)
	/usr/local/go/src/net/textproto/reader.go:36 +0x2b
net/textproto.(*Reader).readCodeLine(0xc000227dd0, 0xe2, 0x0, 0x0, 0xc0000cbb18, 0x511b3f, 0xc000106100, 0x0)
	/usr/local/go/src/net/textproto/reader.go:177 +0x2f
net/textproto.(*Reader).ReadResponse(0xc000227dd0, 0xe2, 0x0, 0xc0000cbbb8, 0x18, 0xc000644a80, 0x1325f68)
	/usr/local/go/src/net/textproto/reader.go:255 +0x4d
github.com/jlaffaye/ftp.(*Response).Close(0xc0005b6020, 0x5, 0xc0000cbc70)
	/root/go/pkg/mod/github.com/jlaffaye/ftp@v0.0.0-20190126081051-8019e6774408/ftp.go:595 +0x89
github.com/jlaffaye/ftp.(*ServerConn).List(0xc000288a40, 0xc000248000, 0x23, 0xc0008d4000, 0x80e8, 0x9800, 0x0, 0x0)
	/root/go/pkg/mod/github.com/jlaffaye/ftp@v0.0.0-20190126081051-8019e6774408/ftp.go:394 +0x483
github.com/ncw/rclone/backend/ftp.(*Fs).List(0xc0002eec30, 0x0, 0x0, 0x8, 0xc000289680, 0xc00023dd40, 0xc000288f50, 0xc0005fbfb0)
	/containers/deps/rclone/backend/ftp/ftp.go:333 +0x111
github.com/ncw/rclone/fs/list.DirSorted(0x1481300, 0xc0002eec30, 0x145be00, 0x0, 0x0, 0x42cc72, 0xffffffff00000008, 0xc0002899c0, 0x0, 0xc0005fbf48)
	/containers/deps/rclone/fs/list/list.go:23 +0x63
github.com/ncw/rclone/fs/march.(*March).makeListDir.func1(0x0, 0x0, 0xc0002c0da0, 0x0, 0xc00023dd40, 0x0, 0x1)
	/containers/deps/rclone/fs/march/march.go:73 +0x53
github.com/ncw/rclone/fs/march.(*March).processJob.func1(0xc0002c0da0, 0xc000106f00, 0x0, 0x0, 0x0, 0x0, 0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000408e20, ...)
	/containers/deps/rclone/fs/march/march.go:347 +0x6c
created by github.com/ncw/rclone/fs/march.(*March).processJob
	/containers/deps/rclone/fs/march/march.go:345 +0x117dinternal/poll.runtime_pollWait(0x7f0dfcd00e30, 0x72, 0xc0000cb780)
	/usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000346018, 0x72, 0xffffffffffffff00, 0x146c4e0, 0x1d58830)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000346018, 0xc000348000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000346000, 0xc000348000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000346000, 0xc000348000, 0x1000, 0x1000, 0xc000644a80, 0x300000002, 0xc000644a80)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000ec40, 0xc000348000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x68
bufio.(*Reader).fill(0xc000229800)
	/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).ReadSlice(0xc000229800, 0x4a7c0a, 0xc000106100, 0x1, 0xc0000cb900, 0xc0000cb9a0, 0x4a9050)
	/usr/local/go/src/bufio/bufio.go:341 +0x36
bufio.(*Reader).ReadLine(0xc000229800, 0xc0000cba00, 0xc0000cb9e0, 0x43660c, 0xc000644a80, 0x300000002, 0xc000644a80)
	/usr/local/go/src/bufio/bufio.go:370 +0x34
net/textproto.(*Reader).readLineSlice(0xc000227dd0, 0x4406dc, 0xc000106128, 0xc0000cba01, 0x4405bb, 0xc000106128)
	/usr/local/go/src/net/textproto/reader.go:55 +0x6f
net/textproto.(*Reader).ReadLine(0xc000227dd0, 0x0, 0x0, 0xc0000cbab0, 0x4404d9)
	/usr/local/go/src/net/textproto/reader.go:36 +0x2b
net/textproto.(*Reader).readCodeLine(0xc000227dd0, 0xe2, 0x0, 0x0, 0xc0000cbb18, 0x511b3f, 0xc000106100, 0x0)
	/usr/local/go/src/net/textproto/reader.go:177 +0x2f
net/textproto.(*Reader).ReadResponse(0xc000227dd0, 0xe2, 0x0, 0xc0000cbbb8, 0x18, 0xc000644a80, 0x1325f68)
	/usr/local/go/src/net/textproto/reader.go:255 +0x4d
github.com/jlaffaye/ftp.(*Response).Close(0xc0005b6020, 0x5, 0xc0000cbc70)
	/root/go/pkg/mod/github.com/jlaffaye/ftp@v0.0.0-20190126081051-8019e6774408/ftp.go:595 +0x89
github.com/jlaffaye/ftp.(*ServerConn).List(0xc000288a40, 0xc000248000, 0x23, 0xc0008d4000, 0x80e8, 0x9800, 0x0, 0x0)
	/root/go/pkg/mod/github.com/jlaffaye/ftp@v0.0.0-20190126081051-8019e6774408/ftp.go:394 +0x483
github.com/ncw/rclone/backend/ftp.(*Fs).List(0xc0002eec30, 0x0, 0x0, 0x8, 0xc000289680, 0xc00023dd40, 0xc000288f50, 0xc0005fbfb0)
	/containers/deps/rclone/backend/ftp/ftp.go:333 +0x111
github.com/ncw/rclone/fs/list.DirSorted(0x1481300, 0xc0002eec30, 0x145be00, 0x0, 0x0, 0x42cc72, 0xffffffff00000008, 0xc0002899c0, 0x0, 0xc0005fbf48)
	/containers/deps/rclone/fs/list/list.go:23 +0x63
github.com/ncw/rclone/fs/march.(*March).makeListDir.func1(0x0, 0x0, 0xc0002c0da0, 0x0, 0xc00023dd40, 0x0, 0x1)
	/containers/deps/rclone/fs/march/march.go:73 +0x53
github.com/ncw/rclone/fs/march.(*March).processJob.func1(0xc0002c0da0, 0xc000106f00, 0x0, 0x0, 0x0, 0x0, 0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000408e20, ...)
	/containers/deps/rclone/fs/march/march.go:347 +0x6c
created by github.com/ncw/rclone/fs/march.(*March).processJob
	/containers/deps/rclone/fs/march/march.go:345 +0x117d```
