### ISSUE TITLE
"func (*ServerConn) Delete" returns non-nil error value on success

### ISSUE THREAD

**Issue by Amadiro** [jlaffaye/ftp#58]
Upon trying to delete a file, I get

```
panic: 200 OK


goroutine 1 [running]:
panic(0x4fb780, 0xc42000d160)
        /usr/lib/go/src/runtime/panic.go:500 +0x1a1
log.Panicln(0xc420053dd0, 0x1, 0x1)
        /usr/lib/go/src/log/log.go:334 +0xc9
main.DeleteLogFile(0xc420014ae0, 0xc42000ca50, 0xb)
        /home/amadiro/main.go:54 +0x1a0
main.main()
        /home/amadiro/main.go:71 +0x30e
exit status 2
```

Tested against bftpd.

**Comment by corny** [comment]
The panic comes from the `DeleteLogFile()` function. It's not related to this FTP library.
@jlaffaye please close this issue

**Comment by jlaffaye** [comment]
Without code, we can not reproduce.
