### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by Metalnem** [jlaffaye/ftp#97]
Function `parseListLine` panics when called with the argument "000000000x " (notice the space at the end).

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/jlaffaye/ftp.parseHostedFTPLine(0x10e3042, 0xb, 0x114c200, 0xc4200107d0, 0xc420010701)
	/Users/Metalnem/Go/src/github.com/jlaffaye/ftp/parse.go:196 +0x24a
github.com/jlaffaye/ftp.parseListLine(0x10e3042, 0xb, 0xc4200107d0, 0x0, 0x0)
	/Users/Metalnem/Go/src/github.com/jlaffaye/ftp/parse.go:209 +0x68
github.com/jlaffaye/ftp.SuperParseLine(0x10e3042, 0xb, 0xc420014630, 0x29, 0xc420014630)
	/Users/Metalnem/Go/src/github.com/jlaffaye/ftp/parse.go:218 +0x35
main.main()
	/Users/Metalnem/Go/src/github.com/jlaffaye/ftp/main/main.go:12 +0x3a
exit status 2
```

This bug was found with the help of [go-fuzz](https://github.com/dvyukov/go-fuzz).

**Comment by corny** [comment]
Nice tool! We should add it to our automated test.
